metadata:
  annotations:
spec:
  replicas: 1
  template:
    spec:            
      volumes:
        - name: cacerts-volume
          configMap:               
            name: cacerts
      containers:
        - volumeMounts:
          - name: cacerts-volume
            mountPath: /deployment/config
          env:
            - name: JAVA_OPTIONS
              value: "-Djavax.net.ssl.trustStore=/deployment/config/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
            
        